# Generated by Django 6.0.3 on 2026-03-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pphone', models.IntegerField()),
                ('eemail', models.EmailField(max_length=254)),
                ('bookingdate', models.DateField()),
                ('bookedon', models.DateField(auto_now=True)),
                ('docname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
